secretsExporter:
  enabled: true
  podSecurityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  securityContext:
    readOnlyRootFilesystem: true
    allowPrivilegeEscalation: false
    capabilities:
      drop: ["ALL"]

hostPathsExporter:
  daemonSets: {}

prometheusPodMonitor:
  create: false

prometheusServiceMonitor:
  create: true
  extraLabels:
    openshift.io/cluster-monitoring: "true"

rbac:
  create: true
  secretsExporter:
    serviceAccountName: x509-certificate-exporter
